image_finetune: false

output_dir: "outputs"
pretrained_model_path: "models/StableDiffusion"

unet_additional_kwargs:
  use_inflated_groupnorm:         true
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention:    false
  use_motion_module:              true
  motion_module_resolutions:      [1,2,4,8]
  motion_module_mid_block:        true
  motion_module_decoder_only:     false
  motion_module_type:             "Vanilla"

  motion_module_kwargs:
    num_attention_heads:                8
    num_transformer_block:              1
    attention_block_types:              [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding:         true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div:         1


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "data/animated_diff_ds_1704830780_batch_1_2_3.csv"
  video_folder:    "data/"
  sample_size:     256
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "A gaming sprite sheet animation of a giant scary blue color Monster with a big hammer in hand, idle state, pixel art animation, 8-bit style, inspired by 16-bit era RPGs games, straight-on camera, with transparent black background."
    - "A gaming sprite sheet animation of a street fighter style male character fully of muscle, attack action, realistic style, front view, close-up, HDR lighting (vivid colors:1.5) (dynamic motion:1.25) (high resolution:1.3), transparent black background.."

  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: "models/Motion_Module/mm_sd_v15_v2.ckpt"
dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors"


learning_rate:    1.e-4
train_batch_size: 4

max_train_epoch:      -1
max_train_steps:      10000
checkpointing_epochs: -1
checkpointing_steps:  5000

validation_steps:       100
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False



